### ISSUE TITLE
Ашибка

### ISSUE THREAD

**Issue by Mottm** [aeonixlegit/PixelX#1]
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- C:\Users\Username\Desktop\PixelX-master\node_modules\canvas\lib\bindings.js
- C:\Users\Username\Desktop\PixelX-master\node_modules\canvas\lib\canvas.js
- C:\Users\Username\Desktop\PixelX-master\node_modules\canvas\index.js
- C:\Users\Username\Desktop\PixelX-master\core.js
- C:\Users\Username\Desktop\PixelX-master\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:685:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:838:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\Username\Desktop\PixelX-master\node_modules\[4mcanvas[24m\lib\bindings.js:3:18)
[90m    at Module._compile (internal/modules/cjs/loader.js:945:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:798:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:711:12)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:838:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Username\\Desktop\\PixelX-master\\node_modules\\canvas\\lib\\bindings.js'[39m,
    [32m'C:\\Users\\Username\\Desktop\\PixelX-master\\node_modules\\canvas\\lib\\canvas.js'[39m,
    [32m'C:\\Users\\Username\\Desktop\\PixelX-master\\node_modules\\canvas\\index.js'[39m,
    [32m'C:\\Users\\Username\\Desktop\\PixelX-master\\core.js'[39m,
    [32m'C:\\Users\\Username\\Desktop\\PixelX-master\\index.js'[39m

**Comment by Mottm** [comment]
Пофиксила переустановка модулей.
/del

**Comment by Mottm** [comment]
> Производится запуск [PixelX - github.com/aeonixlegit/PixelX]
> Bot started.
> Image was loaded.
> Pixels was loaded.
> Bot started.
> Bot started.
> Image was loaded.
> Pixels was loaded.
> Bot started.
Для продолжения нажмите любую клавишу . . .
Ща от админа запущу и затещу

**Comment by Mottm** [comment]
От админа тоже самое

**Comment by Tails-Dev** [comment]
Работает?

**Comment by aeonixlegit** [comment]
Фикс.
