### ISSUE TITLE
не ставит пиксели

### ISSUE THREAD

**Issue by orlikmw** [aeonixlegit/PixelX#3]
Мне кажется или в store.js должно быть больше чем
 module.exports = {
  initPixelCanvas: null,
}
ты случайно лишнего не удалил?

**Comment by Tails-Dev** [comment]
Реально похоже, что какая то часть отсутствует, т.к. это можно было бы уместить в core.js

**Comment by aeonixlegit** [comment]
Дупликат #2.
Лишнего не удалял.
