### ISSUE TITLE
Проблема с координатами

### ISSUE THREAD

**Issue by orlikmw** [aeonixlegit/PixelX#7]
Определяются координаты неверно, если сделать шаблон где пиксель есть ток на нулевых вылетает нахой.

**Comment by orlikmw** [comment]
съезжает вниз и вправо насколько сильно хз

**Comment by orlikmw** [comment]
весь трабл в core.js 117 строка пока не могу понять в чем, не могу поянть смысл данной функции

**Comment by aeonixlegit** [comment]
117 строка - выбор случайных координат из списка для придания реалистичности движениям бота.
