### ISSUE TITLE
После подключения к WebSocket'у Start.bat останавливается

### ISSUE THREAD

**Issue by Tails-Dev** [aeonixlegit/PixelX#8]
Запускаю Start.bat
Жду 5 секунд
Вывод:
`
> Производится запуск [PixelX - github.com/aeonixlegit/PixelX]
> Производится запуск скрипта.
> Бот запущен.
> Состояние полотна обновлено,
> Шаблон обнолен.
> Код решён: 1069
> Подключение к WebSocket было успешным.
Для продолжения нажмите любую клавишу . . .
`

**Comment by aeonixlegit** [comment]
ВКонтакте шалит, всё равно скоро PixelBattle закончится.

**Comment by Tails-Dev** [comment]
Окей, в следующем году можно будет использовать этого бота? И можно помочь с его разработкой?

**Comment by aeonixlegit** [comment]
Скорее всего да, но новый год - новая защита от ботов.

**Comment by aeonixlegit** [comment]
Фикс в последнем коммите.
